name: Jekyll site CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: set ssh key # 临时设置 ssh key
        run: |
          mkdir -p ~/.ssh/
          echo "${{secrets.PRIVATE_KEY}}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p ${{secrets.PORT}} ${{secrets.HOST}} >> ~/.ssh/known_hosts

      - name: deploy
        run: |
          ssh -p ${{secrets.PORT}} root@${{secrets.HOST}} "
              cd /code/sunlight-manga ; # 事先 git clone ** server 分支**
              git checkout . ; # 清空所有改动
              git pull origin master ; # 拉取更新
              npm install ;
              npm run build ;
              cp -r ./dist/* /www/wwwroot/manga.ll2.ink ;
              cp -r ./php /www/wwwroot/manga.ll2.ink ;
          "

